import React, { createContext, useState, useContext, ReactNode, useCallback, useMemo } from 'react';

// Define available languages
export const languages = {
  en: { name: 'English', flag: '🇺🇸' },
  es: { name: 'Español', flag: '🇪🇸' },
  fr: { name: 'Français', flag: '🇫🇷' },
  de: { name: 'Deutsch', flag: '🇩🇪' },
  ja: { name: '日本語', flag: '🇯🇵' },
};
export type LanguageCode = keyof typeof languages;

// Embed translations directly to avoid pathing and module resolution issues
const allTranslations = {
  en: {
    "sidebar_home": "Home",
    "sidebar_explore": "Explore",
    "sidebar_live": "Live",
    "sidebar_communities": "Communities",
    "sidebar_sponsorships": "Sponsorship",
    "sidebar_followers": "Followers",
    "sidebar_notifications": "Notifications",
    "sidebar_messages": "Messages",
    "sidebar_bookmarks": "Bookmarks",
    "sidebar_store": "Store",
    "sidebar_profile": "Profile",
    "sidebar_post_button": "Post",
    "profile_menu_communities": "Communities",
    "profile_menu_ad_manager": "Ad Manager",
    "profile_menu_analytics": "Analytics",
    "profile_menu_monetization": "Monetization",
    "profile_menu_watch_and_earn": "Watch & Earn",
    "profile_menu_verification": "Verification",
    "profile_menu_privacy": "Privacy and Safety",
    "profile_menu_language": "Language",
    "profile_menu_display": "Display",
    "profile_menu_settings": "Settings",
    "profile_menu_qr_code": "QR Code",
    "profile_menu_add_account": "Add an existing account",
    "profile_menu_logout": "Log out {handle}",
    "profile_menu_logout_simple": "Log out",
    "trends_title": "Trends for you",
    "trends_search_placeholder": "Search",
    "trends_show_more": "Show more",
    "trends_category_tech": "Technology",
    "trends_category_webdev": "Web Development",
    "trends_category_ai": "Artificial Intelligence",
    "trends_category_design": "Design",
    "feed_tabs_foryou": "For You",
    "feed_tabs_following": "Following",
    "feed_tabs_store": "Store",
    "feed_reached_end": "You've reached the end",
    "follow_suggestions_title": "Suggested for you",
    "button_follow": "Follow",
    "compose_placeholder": "What is happening?!",
    "compose_post_to": "Post to:",
    "compose_your_profile": "Your Profile",
    "compose_suggestion_title": "Suggestion",
    "compose_dismiss_suggestion": "Dismiss suggestion",
    "compose_use_suggestion": "Use Suggestion",
    "compose_schedule_for": "Schedule for",
    "button_post": "Post",
    "button_schedule": "Schedule",
    "button_save": "Save",
    "post_sponsored": "Sponsored",
    "post_subscriber_only": "Subscriber-only Post",
    "post_subscriber_only_prompt": "Subscribe to {name} to see this post and get access to other exclusive content.",
    "button_subscribe_for": "Subscribe for ${price}/mo",
    "post_posted_in": "Posted in c/{communityName}",
    "post_menu_edit": "Edit Post",
    "post_edited": "edited",
    "profile_posts_count": "{count} posts",
    "button_edit_profile": "Edit Profile",
    "button_subscribed": "Subscribed",
    "profile_following": "Following",
    "profile_followers": "Followers",
    "auth_signin_title": "Sign in to Cascade",
    "auth_email_or_handle": "Email or Handle",
    "auth_password": "Password",
    "button_signin": "Sign in",
    "auth_no_account": "Don't have an account?",
    "auth_signup_link": "Sign up",
    "auth_signup_title": "Create your account",
    "auth_name": "Name",
    "auth_handle": "Handle",
    "auth_email": "Email",
    "auth_confirm_password": "Confirm Password",
    "button_create_account": "Create Account",
    "auth_have_account": "Already have an account?",
    "auth_signin_link": "Sign in",
    "auth_error_all_fields": "Please fill in all fields.",
    "auth_error_passwords_mismatch": "Passwords do not match.",
    "auth_error_handle_taken": "Handle is already taken.",
    "auth_error_email_exists": "An account with this email already exists.",
    "auth_error_invalid_credentials": "Invalid credentials. Please try again.",
    "auth_error_disabled": "This account has been disabled for violating community guidelines.",
    "ask_ai": "Ask AI",
    "privacy_title": "Privacy and Safety",
    "privacy_description": "Manage what information you see and share on Cascade.",
    "privacy_dms_title": "Direct Messages",
    "privacy_dms_description": "Control who can send you direct messages.",
    "privacy_dms_everyone": "Everyone",
    "privacy_dms_following": "People you follow",
    "privacy_dms_none": "No one",
    "privacy_calls_title": "Calls",
    "privacy_calls_description": "Control who can call you.",
    "privacy_allow_audio": "Allow audio calls",
    "privacy_allow_video": "Allow video calls",
    "chat_dms_disabled": "This user is not receiving messages right now.",
    "chat_calls_disabled": "This user has disabled calls.",
    "theme_light": "Light",
    "theme_dark": "Dark",
    "theme_system": "System default",
    "settings_title": "Settings",
    "settings_description": "Manage your account, privacy, and display options.",
    "settings_your_account": "Your Account",
    "settings_your_account_desc": "See your account information and manage settings.",
    "settings_privacy": "Privacy and Safety",
    "settings_privacy_desc": "Control who can see your content and message you.",
    "settings_display": "Display",
    "settings_display_desc": "Customize your view with themes and display options.",
    "settings_language": "Language",
    "settings_language_desc": "Choose the language for your experience.",
    "settings_qr_code_desc": "View and share your profile QR code.",
    "wallet_title": "Wallet",
    "wallet_description": "Manage your coin balance and view transaction history.",
    "wallet_current_balance": "Current Balance",
    "wallet_buy_coins": "Buy Coins",
    "wallet_transaction_history": "Transaction History",
    "wallet_no_transactions": "No transactions yet.",
    "share_echo": "Echo",
    "share_quote_post": "Quote Post",
    "share_via": "Share post via...",
    "share_copy_link": "Copy link to post",
    "share_to_community": "Share to a Community",
    "button_like": "Like",
    "button_liked": "Liked",
    "button_comment": "Comment",
    "button_share": "Share",
    "post_comments_count": "{count} comments",
    "monetization_watch_earn_title": "Earn Ad Credits",
    "monetization_watch_earn_desc": "Watch short videos from sponsors to add funds to your ad balance.",
    "monetization_watch_earn_button": "Start Watching"
  },
  es: {
    "sidebar_home": "Inicio",
    "sidebar_explore": "Explorar",
    "sidebar_live": "En Vivo",
    "sidebar_communities": "Comunidades",
    "sidebar_sponsorships": "Patrocinio",
    "sidebar_followers": "Seguidores",
    "sidebar_notifications": "Notificaciones",
    "sidebar_messages": "Mensajes",
    "sidebar_bookmarks": "Guardados",
    "sidebar_store": "Tienda",
    "sidebar_profile": "Perfil",
    "sidebar_post_button": "Publicar",
    "profile_menu_communities": "Comunidades",
    "profile_menu_ad_manager": "Gestor de Anuncios",
    "profile_menu_analytics": "Estadísticas",
    "profile_menu_monetization": "Monetización",
    "profile_menu_watch_and_earn": "Ver y Ganar",
    "profile_menu_verification": "Verificación",
    "profile_menu_privacy": "Privacidad y Seguridad",
    "profile_menu_language": "Idioma",
    "profile_menu_display": "Pantalla",
    "profile_menu_settings": "Configuración",
    "profile_menu_qr_code": "Código QR",
    "profile_menu_add_account": "Añadir una cuenta existente",
    "profile_menu_logout": "Cerrar sesión de {handle}",
    "profile_menu_logout_simple": "Cerrar sesión",
    "trends_title": "Tendencias para ti",
    "trends_search_placeholder": "Buscar",
    "trends_show_more": "Mostrar más",
    "trends_category_tech": "Tecnología",
    "trends_category_webdev": "Desarrollo Web",
    "trends_category_ai": "Inteligencia Artificial",
    "trends_category_design": "Diseño",
    "feed_tabs_foryou": "Para ti",
    "feed_tabs_following": "Siguiendo",
    "feed_tabs_store": "Tienda",
    "feed_reached_end": "Has llegado al final",
    "follow_suggestions_title": "A quién seguir",
    "button_follow": "Seguir",
    "compose_placeholder": "¿Qué está pasando?",
    "compose_post_to": "Publicar en:",
    "compose_your_profile": "Tu Perfil",
    "compose_suggestion_title": "Sugerencia",
    "compose_dismiss_suggestion": "Descartar sugerencia",
    "compose_use_suggestion": "Usar Sugerencia",
    "compose_schedule_for": "Programar para",
    "button_post": "Publicar",
    "button_schedule": "Programar",
    "button_save": "Guardar",
    "post_sponsored": "Patrocinado",
    "post_subscriber_only": "Publicación solo para suscriptores",
    "post_subscriber_only_prompt": "Suscríbete a {name} para ver esta publicación y acceder a otro contenido exclusivo.",
    "button_subscribe_for": "Suscribirse por ${price}/mes",
    "post_posted_in": "Publicado en c/{communityName}",
    "post_menu_edit": "Editar Publicación",
    "post_edited": "editado",
    "profile_posts_count": "{count} publicaciones",
    "button_edit_profile": "Editar Perfil",
    "button_subscribed": "Suscrito",
    "profile_following": "Siguiendo",
    "profile_followers": "Seguidores",
    "auth_signin_title": "Iniciar sesión en Cascade",
    "auth_email_or_handle": "Correo o Usuario",
    "auth_password": "Contraseña",
    "button_signin": "Iniciar sesión",
    "auth_no_account": "¿No tienes una cuenta?",
    "auth_signup_link": "Regístrate",
    "auth_signup_title": "Crea tu cuenta",
    "auth_name": "Nombre",
    "auth_handle": "Usuario",
    "auth_email": "Correo electrónico",
    "auth_confirm_password": "Confirmar Contraseña",
    "button_create_account": "Crear Cuenta",
    "auth_have_account": "¿Ya tienes una cuenta?",
    "auth_signin_link": "Iniciar sesión",
    "auth_error_all_fields": "Por favor, rellena todos los campos.",
    "auth_error_passwords_mismatch": "Las contraseñas no coinciden.",
    "auth_error_handle_taken": "El usuario ya está en uso.",
    "auth_error_email_exists": "Ya existe una cuenta con este correo.",
    "auth_error_invalid_credentials": "Credenciales inválidas. Inténtalo de nuevo.",
    "auth_error_disabled": "Esta cuenta ha sido deshabilitada por violar las normas de la comunidad.",
    "ask_ai": "Preguntar IA",
    "privacy_title": "Privacidad y Seguridad",
    "privacy_description": "Gestiona qué información ves y compartes en Cascade.",
    "privacy_dms_title": "Mensajes Directos",
    "privacy_dms_description": "Controla quién puede enviarte mensajes directos.",
    "privacy_dms_everyone": "Todos",
    "privacy_dms_following": "Gente que sigues",
    "privacy_dms_none": "Nadie",
    "privacy_calls_title": "Llamadas",
    "privacy_calls_description": "Controla quién puede llamarte.",
    "privacy_allow_audio": "Permitir llamadas de audio",
    "privacy_allow_video": "Permitir videollamadas",
    "chat_dms_disabled": "Este usuario no recibe mensajes en este momento.",
    "chat_calls_disabled": "Este usuario ha desactivado las llamadas.",
    "theme_light": "Claro",
    "theme_dark": "Oscuro",
    "theme_system": "Predeterminado del sistema",
    "settings_title": "Configuración",
    "settings_description": "Gestiona tu cuenta, privacidad y opciones de visualización.",
    "settings_your_account": "Tu Cuenta",
    "settings_your_account_desc": "Ve la información de tu cuenta y gestiona la configuración.",
    "settings_privacy": "Privacidad y Seguridad",
    "settings_privacy_desc": "Controla quién puede ver tu contenido y enviarte mensajes.",
    "settings_display": "Pantalla",
    "settings_display_desc": "Personaliza tu vista con temas y opciones de visualización.",
    "settings_language": "Idioma",
    "settings_language_desc": "Elige el idioma para tu experiencia.",
    "settings_qr_code_desc": "Ver y compartir el código QR de tu perfil.",
    "wallet_title": "Cartera",
    "wallet_description": "Administra tu saldo de monedas y ve el historial de transacciones.",
    "wallet_current_balance": "Saldo Actual",
    "wallet_buy_coins": "Comprar Monedas",
    "wallet_transaction_history": "Historial de Transacciones",
    "wallet_no_transactions": "Aún no hay transacciones.",
    "share_echo": "Hacer eco",
    "share_quote_post": "Citar Publicación",
    "share_via": "Compartir publicación vía...",
    "share_copy_link": "Copiar enlace a la publicación",
    "share_to_community": "Compartir en una Comunidad",
    "button_like": "Me gusta",
    "button_liked": "Ya me gusta",
    "button_comment": "Comentar",
    "button_share": "Compartir",
    "post_comments_count": "{count} comentarios",
    "monetization_watch_earn_title": "Gana Créditos de Anuncios",
    "monetization_watch_earn_desc": "Mira videos cortos de patrocinadores para agregar fondos a tu saldo de anuncios.",
    "monetization_watch_earn_button": "Empezar a Ver"
  },
  fr: {
    "sidebar_home": "Accueil",
    "sidebar_explore": "Explorer",
    "sidebar_live": "En direct",
    "sidebar_communities": "Communautés",
    "sidebar_sponsorships": "Parrainage",
    "sidebar_followers": "Abonnés",
    "sidebar_notifications": "Notifications",
    "sidebar_messages": "Messages",
    "sidebar_bookmarks": "Signets",
    "sidebar_store": "Boutique",
    "sidebar_profile": "Profil",
    "sidebar_post_button": "Publier",
    "profile_menu_communities": "Communautés",
    "profile_menu_ad_manager": "Gestionnaire de pubs",
    "profile_menu_analytics": "Statistiques",
    "profile_menu_monetization": "Monétisation",
    "profile_menu_watch_and_earn": "Regarder et Gagner",
    "profile_menu_verification": "Vérification",
    "profile_menu_privacy": "Confidentialité et sécurité",
    "profile_menu_language": "Langue",
    "profile_menu_display": "Affichage",
    "profile_menu_settings": "Paramètres",
    "profile_menu_qr_code": "Code QR",
    "profile_menu_add_account": "Ajouter un compte existant",
    "profile_menu_logout": "Déconnexion de {handle}",
    "profile_menu_logout_simple": "Déconnexion",
    "trends_title": "Tendances pour vous",
    "trends_search_placeholder": "Rechercher",
    "trends_show_more": "Voir plus",
    "trends_category_tech": "Technologie",
    "trends_category_webdev": "Développement Web",
    "trends_category_ai": "Intelligence Artificielle",
    "trends_category_design": "Design",
    "feed_tabs_foryou": "Pour vous",
    "feed_tabs_following": "Abonnements",
    "feed_tabs_store": "Boutique",
    "feed_reached_end": "Vous avez atteint la fin",
    "follow_suggestions_title": "Qui suivre",
    "button_follow": "Suivre",
    "compose_placeholder": "Quoi de neuf ?",
    "compose_post_to": "Publier sur :",
    "compose_your_profile": "Votre Profil",
    "compose_suggestion_title": "Suggestion",
    "compose_dismiss_suggestion": "Rejeter la suggestion",
    "compose_use_suggestion": "Utiliser la suggestion",
    "compose_schedule_for": "Programmer pour",
    "button_post": "Publier",
    "button_schedule": "Programmer",
    "button_save": "Enregistrer",
    "post_sponsored": "Sponsorisé",
    "post_subscriber_only": "Post pour abonnés",
    "post_subscriber_only_prompt": "Abonnez-vous à {name} pour voir ce post et accéder à d'autres contenus exclusifs.",
    "button_subscribe_for": "S'abonner pour ${price}/mois",
    "post_posted_in": "Publié dans c/{communityName}",
    "post_menu_edit": "Modifier la publication",
    "post_edited": "modifié",
    "profile_posts_count": "{count} publications",
    "button_edit_profile": "Modifier le profil",
    "button_subscribed": "Abonné",
    "profile_following": "Abonnements",
    "profile_followers": "Abonnés",
    "auth_signin_title": "Connexion à Cascade",
    "auth_email_or_handle": "E-mail ou identifiant",
    "auth_password": "Mot de passe",
    "button_signin": "Se connecter",
    "auth_no_account": "Pas de compte ?",
    "auth_signup_link": "Inscrivez-vous",
    "auth_signup_title": "Créez votre compte",
    "auth_name": "Nom",
    "auth_handle": "Identifiant",
    "auth_email": "E-mail",
    "auth_confirm_password": "Confirmer le mot de passe",
    "button_create_account": "Créer un compte",
    "auth_have_account": "Déjà un compte ?",
    "auth_signin_link": "Se connecter",
    "auth_error_all_fields": "Veuillez remplir tous les champs.",
    "auth_error_passwords_mismatch": "Les mots de passe ne correspondent pas.",
    "auth_error_handle_taken": "Cet identifiant est déjà pris.",
    "auth_error_email_exists": "Un compte avec cet e-mail existe déjà.",
    "auth_error_invalid_credentials": "Identifiants incorrects. Veuillez réessayer.",
    "auth_error_disabled": "Ce compte a été désactivé pour violation des règles de la communauté.",
    "ask_ai": "Demander à l'IA",
    "privacy_title": "Confidentialité et sécurité",
    "privacy_description": "Gérez les informations que vous voyez et partagez sur Cascade.",
    "privacy_dms_title": "Messages privés",
    "privacy_dms_description": "Contrôlez qui peut vous envoyer des messages privés.",
    "privacy_dms_everyone": "Tout le monde",
    "privacy_dms_following": "Personnes que vous suivez",
    "privacy_dms_none": "Personne",
    "privacy_calls_title": "Appels",
    "privacy_calls_description": "Contrôlez qui peut vous appeler.",
    "privacy_allow_audio": "Autoriser les appels audio",
    "privacy_allow_video": "Autoriser les appels vidéo",
    "chat_dms_disabled": "Cet utilisateur ne reçoit pas de messages pour le moment.",
    "chat_calls_disabled": "Cet utilisateur a désactivé les appels.",
    "theme_light": "Clair",
    "theme_dark": "Sombre",
    "theme_system": "Par défaut du système",
    "settings_title": "Paramètres",
    "settings_description": "Gérez votre compte, votre confidentialité et vos options d'affichage.",
    "settings_your_account": "Votre compte",
    "settings_your_account_desc": "Consultez les informations de votre compte et gérez les paramètres.",
    "settings_privacy": "Confidentialité et sécurité",
    "settings_privacy_desc": "Contrôlez qui peut voir votre contenu et vous envoyer des messages.",
    "settings_display": "Affichage",
    "settings_display_desc": "Personnalisez votre affichage avec des thèmes et des options.",
    "settings_language": "Langue",
    "settings_language_desc": "Choisissez la langue de votre expérience.",
    "settings_qr_code_desc": "Voir et partager le code QR de votre profil.",
    "wallet_title": "Portefeuille",
    "wallet_description": "Gérez votre solde de pièces et consultez l'historique des transactions.",
    "wallet_current_balance": "Solde Actuel",
    "wallet_buy_coins": "Acheter des Pièces",
    "wallet_transaction_history": "Historique des Transactions",
    "wallet_no_transactions": "Aucune transaction pour le moment.",
    "share_echo": "Écho",
    "share_quote_post": "Citer la publication",
    "share_via": "Partager la publication via...",
    "share_copy_link": "Copier le lien de la publication",
    "share_to_community": "Partager dans une Communauté",
    "button_like": "J'aime",
    "button_liked": "Aimé",
    "button_comment": "Commenter",
    "button_share": "Partager",
    "post_comments_count": "{count} commentaires",
    "monetization_watch_earn_title": "Gagnez des Crédits Publicitaires",
    "monetization_watch_earn_desc": "Regardez de courtes vidéos de sponsors pour ajouter des fonds à votre solde publicitaire.",
    "monetization_watch_earn_button": "Commencer à Regarder"
  },
  de: {
    "sidebar_home": "Startseite",
    "sidebar_explore": "Entdecken",
    "sidebar_live": "Live",
    "sidebar_communities": "Communitys",
    "sidebar_sponsorships": "Sponsoring",
    "sidebar_followers": "Follower",
    "sidebar_notifications": "Benachrichtigungen",
    "sidebar_messages": "Nachrichten",
    "sidebar_bookmarks": "Lesezeichen",
    "sidebar_store": "Shop",
    "sidebar_profile": "Profil",
    "sidebar_post_button": "Posten",
    "profile_menu_communities": "Communitys",
    "profile_menu_ad_manager": "Anzeigenmanager",
    "profile_menu_analytics": "Analysen",
    "profile_menu_monetization": "Monetarisierung",
    "profile_menu_watch_and_earn": "Ansehen & Verdienen",
    "profile_menu_verification": "Verifizierung",
    "profile_menu_privacy": "Datenschutz & Sicherheit",
    "profile_menu_language": "Sprache",
    "profile_menu_display": "Anzeige",
    "profile_menu_settings": "Einstellungen",
    "profile_menu_qr_code": "QR-Code",
    "profile_menu_add_account": "Bestehendes Konto hinzufügen",
    "profile_menu_logout": "Von {handle} abmelden",
    "profile_menu_logout_simple": "Abmelden",
    "trends_title": "Trends für dich",
    "trends_search_placeholder": "Suchen",
    "trends_show_more": "Mehr anzeigen",
    "trends_category_tech": "Technologie",
    "trends_category_webdev": "Webentwicklung",
    "trends_category_ai": "Künstliche Intelligenz",
    "trends_category_design": "Design",
    "feed_tabs_foryou": "Für dich",
    "feed_tabs_following": "Folge ich",
    "feed_tabs_store": "Shop",
    "feed_reached_end": "Du hast das Ende erreicht",
    "follow_suggestions_title": "Wem folgen?",
    "button_follow": "Folgen",
    "compose_placeholder": "Was passiert gerade?",
    "compose_post_to": "Posten in:",
    "compose_your_profile": "Dein Profil",
    "compose_suggestion_title": "Vorschlag",
    "compose_dismiss_suggestion": "Vorschlag verwerfen",
    "compose_use_suggestion": "Vorschlag verwenden",
    "compose_schedule_for": "Planen für",
    "button_post": "Posten",
    "button_schedule": "Planen",
    "button_save": "Speichern",
    "post_sponsored": "Gesponsert",
    "post_subscriber_only": "Post nur für Abonnenten",
    "post_subscriber_only_prompt": "Abonniere {name}, um diesen Post zu sehen und Zugang zu exklusiven Inhalten zu erhalten.",
    "button_subscribe_for": "Abonnieren für ${price}/Monat",
    "post_posted_in": "Gepostet in c/{communityName}",
    "post_menu_edit": "Beitrag bearbeiten",
    "post_edited": "bearbeitet",
    "profile_posts_count": "{count} Beiträge",
    "button_edit_profile": "Profil bearbeiten",
    "button_subscribed": "Abonniert",
    "profile_following": "Folge ich",
    "profile_followers": "Follower",
    "auth_signin_title": "Bei Cascade anmelden",
    "auth_email_or_handle": "E-Mail oder Benutzername",
    "auth_password": "Passwort",
    "button_signin": "Anmelden",
    "auth_no_account": "Kein Konto?",
    "auth_signup_link": "Registrieren",
    "auth_signup_title": "Konto erstellen",
    "auth_name": "Name",
    "auth_handle": "Benutzername",
    "auth_email": "E-Mail",
    "auth_confirm_password": "Passwort bestätigen",
    "button_create_account": "Konto erstellen",
    "auth_have_account": "Bereits ein Konto?",
    "auth_signin_link": "Anmelden",
    "auth_error_all_fields": "Bitte alle Felder ausfüllen.",
    "auth_error_passwords_mismatch": "Die Passwörter stimmen nicht überein.",
    "auth_error_handle_taken": "Benutzername ist bereits vergeben.",
    "auth_error_email_exists": "Ein Konto mit dieser E-Mail existiert bereits.",
    "auth_error_invalid_credentials": "Ungültige Anmeldedaten. Bitte versuche es erneut.",
    "auth_error_disabled": "Dieses Konto wurde wegen eines Verstoßes gegen die Community-Richtlinien deaktiviert.",
    "ask_ai": "KI fragen",
    "privacy_title": "Datenschutz & Sicherheit",
    "privacy_description": "Verwalte, welche Informationen du auf Cascade siehst und teilst.",
    "privacy_dms_title": "Direktnachrichten",
    "privacy_dms_description": "Kontrolliere, wer dir Direktnachrichten senden kann.",
    "privacy_dms_everyone": "Jeder",
    "privacy_dms_following": "Personen, denen du folgst",
    "privacy_dms_none": "Niemand",
    "privacy_calls_title": "Anrufe",
    "privacy_calls_description": "Kontrolliere, wer dich anrufen kann.",
    "privacy_allow_audio": "Audioanrufe zulassen",
    "privacy_allow_video": "Videoanrufe zulassen",
    "chat_dms_disabled": "Dieser Benutzer empfängt derzeit keine Nachrichten.",
    "chat_calls_disabled": "Dieser Benutzer hat Anrufe deaktiviert.",
    "theme_light": "Hell",
    "theme_dark": "Dunkel",
    "theme_system": "Systemstandard",
    "settings_title": "Einstellungen",
    "settings_description": "Verwalten Sie Ihr Konto, Ihre Privatsphäre und Ihre Anzeigeoptionen.",
    "settings_your_account": "Ihr Konto",
    "settings_your_account_desc": "Sehen Sie Ihre Kontoinformationen und verwalten Sie die Einstellungen.",
    "settings_privacy": "Datenschutz & Sicherheit",
    "settings_privacy_desc": "Kontrollieren Sie, wer Ihre Inhalte sehen und Ihnen Nachrichten senden kann.",
    "settings_display": "Anzeige",
    "settings_display_desc": "Passen Sie Ihre Ansicht mit Themen und Anzeigeoptionen an.",
    "settings_language": "Sprache",
    "settings_language_desc": "Wählen Sie die Sprache für Ihre Erfahrung.",
    "settings_qr_code_desc": "Ihren Profil-QR-Code anzeigen und teilen.",
    "wallet_title": "Brieftasche",
    "wallet_description": "Verwalten Sie Ihren Münzsaldo und sehen Sie den Transaktionsverlauf.",
    "wallet_current_balance": "Aktueller Saldo",
    "wallet_buy_coins": "Münzen kaufen",
    "wallet_transaction_history": "Transaktionsverlauf",
    "wallet_no_transactions": "Noch keine Transaktionen.",
    "share_echo": "Echo",
    "share_quote_post": "Beitrag zitieren",
    "share_via": "Beitrag teilen über...",
    "share_copy_link": "Link zum Beitrag kopieren",
    "share_to_community": "In einer Community teilen",
    "button_like": "Gefällt mir",
    "button_liked": "Gefällt",
    "button_comment": "Kommentieren",
    "button_share": "Teilen",
    "post_comments_count": "{count} Kommentare",
    "monetization_watch_earn_title": "Werbeguthaben verdienen",
    "monetization_watch_earn_desc": "Sehen Sie sich kurze Videos von Sponsoren an, um Guthaben zu Ihrem Werbekonto hinzuzufügen.",
    "monetization_watch_earn_button": "Ansehen starten"
  },
  ja: {
    "sidebar_home": "ホーム",
    "sidebar_explore": "話題を検索",
    "sidebar_live": "ライブ",
    "sidebar_communities": "コミュニティ",
    "sidebar_sponsorships": "スポンサーシップ",
    "sidebar_followers": "フォロワー",
    "sidebar_notifications": "通知",
    "sidebar_messages": "メッセージ",
    "sidebar_bookmarks": "ブックマーク",
    "sidebar_store": "ストア",
    "sidebar_profile": "プロフィール",
    "sidebar_post_button": "投稿",
    "profile_menu_communities": "コミュニティ",
    "profile_menu_ad_manager": "広告マネージャー",
    "profile_menu_analytics": "アナリティクス",
    "profile_menu_monetization": "収益化",
    "profile_menu_watch_and_earn": "見て稼ぐ",
    "profile_menu_verification": "認証",
    "profile_menu_privacy": "プライバシーと安全",
    "profile_menu_language": "言語",
    "profile_menu_display": "表示",
    "profile_menu_settings": "設定",
    "profile_menu_qr_code": "QRコード",
    "profile_menu_add_account": "既存のアカウントを追加",
    "profile_menu_logout": "{handle}からログアウト",
    "profile_menu_logout_simple": "ログアウト",
    "trends_title": "おすすめのトレンド",
    "trends_search_placeholder": "検索",
    "trends_show_more": "さらに表示",
    "trends_category_tech": "テクノロジー",
    "trends_category_webdev": "ウェブ開発",
    "trends_category_ai": "人工知能",
    "trends_category_design": "デザイン",
    "feed_tabs_foryou": "おすすめ",
    "feed_tabs_following": "フォロー中",
    "feed_tabs_store": "ストア",
    "feed_reached_end": "これで全部です",
    "follow_suggestions_title": "おすすめユーザー",
    "button_follow": "フォロー",
    "compose_placeholder": "いまどうしてる？",
    "compose_post_to": "投稿先:",
    "compose_your_profile": "あなたのプロフィール",
    "compose_suggestion_title": "提案",
    "compose_dismiss_suggestion": "提案を閉じる",
    "compose_use_suggestion": "提案を使用",
    "compose_schedule_for": "予約設定",
    "button_post": "投稿する",
    "button_schedule": "予約設定",
    "button_save": "保存",
    "post_sponsored": "プロモーション",
    "post_subscriber_only": "サポーター限定の投稿",
    "post_subscriber_only_prompt": "{name}を購読して、この投稿や他の限定コンテンツにアクセスしましょう。",
    "button_subscribe_for": "月額${price}で購読",
    "post_posted_in": "c/{communityName}に投稿",
    "post_menu_edit": "投稿を編集",
    "post_edited": "編集済み",
    "profile_posts_count": "{count}件の投稿",
    "button_edit_profile": "プロフィールを編集",
    "button_subscribed": "購読中",
    "profile_following": "フォロー中",
    "profile_followers": "フォロワー",
    "auth_signin_title": "Cascadeにログイン",
    "auth_email_or_handle": "メールアドレスまたはユーザー名",
    "auth_password": "パスワード",
    "button_signin": "ログイン",
    "auth_no_account": "アカウントをお持ちでないですか？",
    "auth_signup_link": "登録する",
    "auth_signup_title": "アカウントを作成",
    "auth_name": "名前",
    "auth_handle": "ユーザー名",
    "auth_email": "メールアドレス",
    "auth_confirm_password": "パスワードを再入力",
    "button_create_account": "アカウント作成",
    "auth_have_account": "アカウントをお持ちですか？",
    "auth_signin_link": "ログイン",
    "auth_error_all_fields": "すべてのフィールドを入力してください。",
    "auth_error_passwords_mismatch": "パスワードが一致しません。",
    "auth_error_handle_taken": "このユーザー名は既に使用されています。",
    "auth_error_email_exists": "このメールアドレスは既に登録されています。",
    "auth_error_invalid_credentials": "認証情報が無効です。もう一度お試しください。",
    "auth_error_disabled": "このアカウントはコミュニティガイドライン違反のため無効化されています。",
    "ask_ai": "AIに質問",
    "privacy_title": "プライバシーと安全",
    "privacy_description": "Cascadeで表示・共有する情報を管理します。",
    "privacy_dms_title": "ダイレクトメッセージ",
    "privacy_dms_description": "ダイレクトメッセージを送信できるユーザーを管理します。",
    "privacy_dms_everyone": "全員",
    "privacy_dms_following": "フォローしているアカウント",
    "privacy_dms_none": "誰にも許可しない",
    "privacy_calls_title": "通話",
    "privacy_calls_description": "あなたに通話できるユーザーを管理します。",
    "privacy_allow_audio": "音声通話を許可する",
    "privacy_allow_video": "ビデオ通話を許可する",
    "chat_dms_disabled": "このユーザーは現在メッセージを受信していません。",
    "chat_calls_disabled": "このユーザーは通話を無効にしています。",
    "theme_light": "ライト",
    "theme_dark": "ダーク",
    "theme_system": "システムのデフォルト",
    "settings_title": "設定",
    "settings_description": "アカウント、プライバシー、表示オプションを管理します。",
    "settings_your_account": "アカウント",
    "settings_your_account_desc": "アカウント情報を表示し、設定を管理します。",
    "settings_privacy": "プライバシーと安全",
    "settings_privacy_desc": "コンテンツの閲覧やメッセージの送信ができるユーザーを管理します。",
    "settings_display": "表示",
    "settings_display_desc": "テーマや表示オプションでビューをカスタマイズします。",
    "settings_language": "言語",
    "settings_language_desc": "体験に使用する言語を選択します。",
    "settings_qr_code_desc": "あなたのプロフィールのQRコードを表示・共有します。",
    "wallet_title": "ウォレット",
    "wallet_description": "コインの残高を管理し、取引履歴を表示します。",
    "wallet_current_balance": "現在の残高",
    "wallet_buy_coins": "コインを購入",
    "wallet_transaction_history": "取引履歴",
    "wallet_no_transactions": "取引はまだありません。",
    "share_echo": "エコー",
    "share_quote_post": "引用投稿",
    "share_via": "投稿を共有...",
    "share_copy_link": "投稿へのリンクをコピー",
    "share_to_community": "コミュニティに共有",
    "button_like": "いいね！",
    "button_liked": "いいね済み",
    "button_comment": "コメント",
    "button_share": "シェア",
    "post_comments_count": "{count}件のコメント",
    "monetization_watch_earn_title": "広告クレジットを獲得",
    "monetization_watch_earn_desc": "スポンサーの短い動画を視聴して、広告残高に資金を追加します。",
    "monetization_watch_earn_button": "視聴を開始"
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
  locale: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const savedLang = localStorage.getItem('cascade-language');
    return (savedLang && languages[savedLang as LanguageCode]) ? (savedLang as LanguageCode) : 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    localStorage.setItem('cascade-language', lang);
    setLanguageState(lang);
  };

  const t = useCallback((key: string, variables: Record<string, string | number> = {}): string => {
    const translations = allTranslations[language] as Record<string, string> | undefined;
    let translation = translations?.[key] || key;
    Object.keys(variables).forEach(varKey => {
      const regex = new RegExp(`{${varKey}}`, 'g');
      translation = translation.replace(regex, String(variables[varKey]));
    });
    return translation;
  }, [language]);
  
  const locale = useMemo(() => {
    const mapping: Record<LanguageCode, string> = {
        en: 'en-US',
        es: 'es-ES',
        fr: 'fr-FR',
        de: 'de-DE',
        ja: 'ja-JP',
    };
    return mapping[language] || 'en-US';
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, locale }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
